# Generated by Django 5.1.1 on 2024-09-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('partner', 'Partner'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
