# Generated by Django 5.1.1 on 2024-09-21 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deceased', '0010_alter_review_text'),
        ('orders', '0013_remove_order_products_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deceased',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deceased.deceasedperson'),
        ),
    ]
