# Generated by Django 5.1.1 on 2024-09-19 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deceased', '0007_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
