# Generated by Django 5.1.1 on 2024-09-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deceased', '0013_remove_review_profile_url_deceasedperson_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='deceasedperson',
            name='family_tree',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
