# Generated by Django 5.1.1 on 2024-09-18 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_product'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.partner'),
        ),
    ]
