# Generated by Django 5.1.1 on 2024-09-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="products",
        ),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
