# Generated by Django 5.1.1 on 2024-09-21 07:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deceased', '0010_alter_review_text'),
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='deceased',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deceased.deceasedperson'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)]),
        ),
        migrations.AlterField(
            model_name='deceasedtimeline',
            name='deceased',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to='deceased.deceasedperson'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
