# Generated by Django 5.1.1 on 2024-09-25 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deceased', '0013_remove_review_profile_url_deceasedperson_profile_url'),
        ('timeline', '0003_alter_timeline_event_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='family_album/')),
                ('deceased', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_albums', to='deceased.deceasedperson')),
            ],
        ),
    ]
