# Generated by Django 5.1.1 on 2024-09-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeceasedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField()),
                ('date_of_burial', models.DateField(blank=True, null=True)),
                ('relationship_with_deceased', models.CharField(blank=True, max_length=255, null=True)),
                ('headshot', models.ImageField(blank=True, null=True, upload_to='deceased/')),
                ('voice_recording', models.FileField(blank=True, null=True, upload_to='deceased/voice/')),
                ('about', models.TextField(blank=True, null=True)),
                ('quote', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
