# Generated by Django 5.1.1 on 2024-09-16 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deceased', '0004_rename_is_approved_note_approved_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
