# Generated by Django 5.1.1 on 2024-09-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deceased', '0011_rename_text_review_textfield1_review_imagefield1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='profile_url',
            field=models.URLField(default='https://memoria.com'),
        ),
    ]
