# Generated by Django 5.1.1 on 2024-09-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deceased', '0012_review_profile_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='profile_url',
        ),
        migrations.AddField(
            model_name='deceasedperson',
            name='profile_url',
            field=models.URLField(default='https://memoria.com'),
        ),
    ]
